apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-explicit-topic
  labels:
    # This label tells the Strimzi operator which Kafka cluster this topic belongs to.
    strimzi.io/cluster: my-cluster
spec:
  partitions: 12
  replicas: 3
  # -- Topic-specific configurations that override cluster defaults --
  # In this case, we are setting a shorter retention period for this specific topic.
  config:
    # Retention for this topic is 3 days (in milliseconds)
    retention.ms: 259200000
    # You can override any topic-level configuration here.
    segment.bytes: 536870912 # 512 MB
    # 'compact' is used for log compaction, which retains the last known value for each message key.
    # 'delete' (default) discards old log segments when their retention time or size limit is reached.
    cleanup.policy: compact,delete
    # Specifies the compression codec for a given topic.
    # Valid values: 'uncompressed', 'zstd', 'lz4', 'snappy', 'gzip', 'producer' (default).
    compression.type: lz4